on: push
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./
        with:
          # Command
          shopify-command: version
          # Flags
          shopify-flags: -p=${{ secrets.SHOPIFY_PASSWORD }} -s=${{ secrets.SHOPIFY_STORE_URL }} -t=${{ secrets.SHOPIFY_THEME_ID }}
